name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install current package (Validation)
        run: uv pip install . --system

      - name: Test Project Generation & Validate
        run: |
          # Use ocd to generate a project
          ocd init myproject --all
          cd myproject/backend
          uv sync
          # Run check and migrations to catch everything we missed (labels, missing deps, etc)
          uv run python manage.py check
          uv run python manage.py makemigrations --check

      - name: Build and Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uv publish

